name: openscvx
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - termcolor
  - plotly
  - scipy
  - pyqtgraph
  - pyqt
  - pip:
      - jax
      - cvxpy
      - cvxpygen
      - qoco
      - qocogen
      - diffrax
      - absl-py
      - flatbuffers
