site_name: OpenSCvx
site_url: https://haynec.github.io/OpenSCvx
site_author: Chris Hayner
site_description: Documentation for OpenSCvx, a Python library for solving nonconvex optimization trajectory optimization problems.
repo_name: haynec/OpenSCvx
repo_url: https://github.com/haynec/OpenSCvx
theme:
  name: material
  icon:
    logo: material/rocket-launch-outline 
    admonition:
      <type>: material/fire
  features:
    - navigation.sections
    - announce.dismiss
    - user_color_mode_toggle
    - header.autohide
    - toc.integrate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: CMU Sans Serif

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: "Â¤"  # Adds a clickable permalink to each section heading
      toc_depth: 2  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _static/custom_css.css

copyright: Copyright &copy; 2025 Chris Hayner

plugins:
  - mkdocstrings:
      setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
            - import jax.tree_util
            - jax.tree_util.Partial.__module__ = "jax.tree_util"
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            members_order: source
            heading_level: 4
            inherited_members: false  # Allow looking up inherited methods
          paths: [src]

nav:
    - 'index.md'
    - Usage:
      - 'Usage/basic_problem_setup.md'
      - 'Usage/advanced_problem_setup.md'
      - 'Usage/api.md'
      - 'Usage/tutorials.md'
    - Foundations:
      - 'Overview/scvx.md'
      - 'Overview/ocp.md'
      - 'Overview/discretization.md'
      - 'Overview/constraint_reformulation.md'
      - 'Overview/control_parameterization.md'
      - 'Overview/time_dilation.md'